<?php require("head.php"); ?>

    <!-- top menu -->
    <nav class="navbar navbar-default navbar-fixed-top  pagesetup">
      <?php require("menu.php"); ?>
    </nav>

    <!-- bottom menu -->
    <nav class="navbar navbar-default  navbar-fixed-bottom pagesetup">
    <?php require("menu.php"); ?>
    </nav>

    <div style="margin-top:50px; padding-top:10px;"></div>
    <!-- main contents   -->

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 ">

            <div class="text-warning h2 bg-info thumbnail">
                <p> We give much value for your money. We work hard so that you can make money but stock market is subject to risk. Do your own research before investing .We do not responsible for your profit or loss </p>
            </div>
            <div class="text-warning h2 bg-info thumbnail">
                <p>This is for your awareness purpose only</p>
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>

<div>
Disclosure / Disclaimer

    1. You will be subscribing with us knowing fully the risk of the stock market.
      You shall alone be responsible for trades carried out on the basis of calls generated by this
      system resulting in the losses or gains, as the case may be.

    2. No legal or otherwise liability will be fixed on us under any circumstances.
      Calls generated by this system are purely based on artificial intelligence & not a professionally
      qualified and expertise view. These Recommendations are based on some formula.
      Due care has been taken while generating these calls, no responsibility will be
      assumed by the author / developer of this system for the consequences what so ever,
      resulting out of acting on these recommendations / calls.

    3. The calls generated by this system are based on formulas and these are not recommendation
      to any person to buy or sell any securities. The information is derived from source
      that are deemed to be reliable but its accuracy and completeness are not guaranteed.
      The author does not accept any liability for the use of this system.

    4. Users of this system who buy or sell securities based on the information in this system are
      solely responsible for their action. We may or may not have any position in given stock.

    5. All prices relate to the NSE, unless otherwise mentioned. We advise users to check
      with certified experts before taking any investment decisions. You are responsible for your own
      investment decisions. If you don't accept this responsibility for yourself,
      then you should not use this system.

    6. If any other entity, individual or service provider also giving the same system
      and recommendation than we are not responsible for that.

    7. We encourage all investors to use the information in this article as a resource only
      to further their own research on all featured companies, stocks, sectors,
      markets and information presented on the article. Nothing written on this article should
      be considered as an investment advice. It's not an offer to buy or sell.

    8. We disclaims any and all liability, current or future, for any error made or omission
      committed with respect to the transmission of such data, information or material
      available on this system. The user waives his or her right to any claim based on the detrimental
      effects or results of any reliance placed by the user on any information or data available on this system.

    9. The information and material contained in these pages and the terms, conditions,
      and descriptions that appear are subject to change without prior notice. Investments
      in equity shares, debentures etc, are not obligations of or guaranteed and
      are subject to investment risks. The information contained in this text, graphics, links or other
      items are provided on an 'as is', 'as available' basis. We do not warrant the accuracy, adequacy
      or completeness of this information and material and expressly disclaims liability for errors or omissions
      in this information and material. No warranty of any kind, implied, express or statutory,
      including but not limited to the warranties of non-infringement of third party rights,
      title, merchantability, fitness for a particular purpose and freedom from computer virus,
      is given in conjunction with the information and Materials. In no event will we
      be liable for any damages, including without limitation direct or indirect, special,
      incidental, or consequential damages, losses or expenses arising in connection with this system
      or use thereof or inability to use by any party, or in connection with any failure of performance,
      error, omission, interruption, defect, delay in operation or transmission, computer virus
      or line or system failure.
</div>
<?php require("foot.php"); ?>